AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  multi-modal-rag-notes-api
Parameters:
  DocumentTable:
    Type: String
    Description: "Documents Table"
  UserTable:
    Type: String
    Description: "Users Table"
  UserNotesTable:
    Type: String
    Description: "User Notes Table"
  AppSyncServiceRole:
    Type: String
    Description: "Appsync Service Role ARN"
  NoteLambdaFunction:
    Type: String
    Description: "Appsync notes lambda function ARN"
  CognitoUserPool:
    Type: String
    Description: "Cognito User Pools"

Resources:
  RoleAppSyncCloudWatch:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com


  NotesAIAPI:
    Type: "AWS::AppSync::GraphQLApi"
    Properties:
        Name: MULTIMODAL_RAG_API
        AuthenticationType: "API_KEY"
        AdditionalAuthenticationProviders:
            - AuthenticationType: AMAZON_COGNITO_USER_POOLS
              UserPoolConfig:
                  AwsRegion: !Ref AWS::Region
                  UserPoolId: !Ref CognitoUserPool
            - AuthenticationType: AWS_IAM
        XrayEnabled: true
        LogConfig:
            CloudWatchLogsRoleArn: !GetAtt RoleAppSyncCloudWatch.Arn
            ExcludeVerboseContent: FALSE
            FieldLogLevel: ALL
  NotesAIApiKey:
      Type: AWS::AppSync::ApiKey
      Properties:
          ApiId: !GetAtt NotesAIAPI.ApiId

  NotesAIAPISchema:
      Type: "AWS::AppSync::GraphQLSchema"
      Properties:
          ApiId: !GetAtt NotesAIAPI.ApiId
          DefinitionS3Location: '../schema/schema.graphql'

  NoteFunctionDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt NotesAIAPI.ApiId
      Name: "NoteLambdaDirectResolver"
      Type: "AWS_LAMBDA"
      ServiceRoleArn: !Ref AppSyncServiceRole

      LambdaConfig:
        LambdaFunctionArn: !Ref NoteLambdaFunction
  AppSyncNotesTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: NoneDataSource
      ApiId: !GetAtt NotesAIAPI.ApiId
      Description: "None"
      Type: NONE
  # Mutation resolver
  AppSyncMutationResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: NotesAIAPISchema
    Properties:
      ApiId: !GetAtt NotesAIAPI.ApiId
      TypeName: Mutation
      FieldName: publish
      DataSourceName: !GetAtt AppSyncNotesTableDataSource.Name
      # Map the request into the desired payload
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "payload": {
              "id": "$context.arguments.id",
              "source": "$context.arguments.source",
              "account": "$context.arguments.account",
              "time": "$context.arguments.time",
              "region": "$context.arguments.region",
              "detailType": "$context.arguments.detailType",
              "data": "$context.arguments.data"
          }
        }
      ResponseMappingTemplate: "$util.toJson($context.result)"
  CreateUserAccountResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt NotesAIAPI.ApiId
      TypeName: "Mutation"
      FieldName: "createUserAccount"
      DataSourceName: !GetAtt NoteFunctionDataSource.Name

  queryDocumentResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt NotesAIAPI.ApiId
      TypeName: "Query"
      FieldName: "queryDocument"
      DataSourceName: !GetAtt NoteFunctionDataSource.Name


  CreateNoteResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt NotesAIAPI.ApiId
      TypeName: "Mutation"
      FieldName: "createNote"
      DataSourceName: !GetAtt NoteFunctionDataSource.Name
  UpdateNoteResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt NotesAIAPI.ApiId
      TypeName: "Mutation"
      FieldName: "updateNote"
      DataSourceName: !GetAtt NoteFunctionDataSource.Name
  getNoteResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt NotesAIAPI.ApiId
      TypeName: "Query"
      FieldName: "getNote"
      DataSourceName: !GetAtt NoteFunctionDataSource.Name
  getNotesResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt NotesAIAPI.ApiId
      TypeName: "Query"
      FieldName: "getAllNotes"
      DataSourceName: !GetAtt NoteFunctionDataSource.Name
  enhanceNoteResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt NotesAIAPI.ApiId
      TypeName: "Query"
      FieldName: "enhanceNote"
      DataSourceName: !GetAtt NoteFunctionDataSource.Name


  ###################
  # OUTPUTS
  ##################
Outputs:

  NotesAIAPIArn:
    Value: !GetAtt NotesAIAPI.Arn
  NotesAIAPIGraphqlArn:
    Value: !GetAtt NotesAIAPI.GraphQLEndpointArn
